wsl/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post 'gradings/:id' => 'gradings#toggle_approval'

  get 'pages/welcome'

  get 'pages/verify'

  get 'gradings/recommendation' => 'gradings#recommendation'

  root 'pages#welcome'
  resources :gradings
  resources :users
  resources :courses
  get '/courses', to:'courses#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

wsl/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all.sort_by { |course| course.coursenum }
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:coursenum, :sectionnum, :coursename, :days, :starttime, :endtime, :enrolled, :waitlist, :user_id)
    end
end

wsl/app/helpers/courses_helper.rb
module CoursesHelper
end

wsl/app/views/courses/_form.html.erb
<% #A partial which displays forms, generated by rails %>

<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coursenum %>
    <%= form.text_field :coursenum %>
  </div>

  <div class="field">
    <%= form.label :sectionnum %>
    <%= form.text_field :sectionnum %>
  </div>

  <div class="field">
    <%= form.label :coursename %>
    <%= form.text_field :coursename %>
  </div>

  <div class="field">
    <%= form.label :days %>
    <%= form.text_field :days %>
  </div>

  <div class="field">
    <%= form.label :starttime %>
    <%= form.text_field :starttime %>
  </div>

  <div class="field">
    <%= form.label :endtime %>
    <%= form.text_field :endtime %>
  </div>

  <div class="field">
    <%= form.label :enrolled %>
    <%= form.number_field :enrolled %>
  </div>

  <div class="field">
    <%= form.label :waitlist %>
    <%= form.number_field :waitlist %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

wsl/app/views/courses/edit.html.erb
<% #Page for editing courses, not used for project 4, generated by rails %>

<% <h1>Editing Course</h1> %>

<% render 'form', course: @course %>

<% link_to 'Show', @course %> |
<% link_to 'Back', courses_path %>

wsl/app/views/courses/index.html.erb
<% # Page that shows table overview of courses, generated by rails %>
<% # Also contains certain links based on type of user signed in %>

<% # If signed-in, show courses table%>
<% if user_signed_in? %>

  <% content_for :title do %>
    Courses
  <% end %>

  <p id="notice"><%= notice %></p>

  <h1>Courses</h1>
  <br />

  <% if current_user.user_type == 1 %>
    <table id="myTable">
  <% else %>
    <table id="myTable" >
  <% end %>

  
    <thead>
      <tr>
        <th>Course #</th>
        <th>Section #</th>
        <th>Course Name</th>
        <th>Meeting Days</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Enrolled</th>
        <th>Waitlist</th>
        <th># Graders</th>
        <% if current_user.user_type == 3 || current_user.user_type == 2 %>
          <th># Applications</th>
        <% end %>
        <th colspan="3">Actions</th>
      </tr>
      <tr id="search-box">
        <th><input type="text" id="col0" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col1" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col2" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col3" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col4" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col5" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col6" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col7" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <th><input type="text" id="col8" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <% if current_user.user_type == 3 || current_user.user_type == 2 %>
          <th><input type="text" id="col9" class="narrow-column" onkeyup="myFunction(this)" title="Type in a name"></th>
        <% end %>
        <th colspan="3">Filters</th>
      </tr>
    </thead>

    <% stu_apps = Grading.where :user_id => current_user.id %>
    <tbody>
      <% @courses.each do |course| %>
        <% graders = Grading.where :course_id => course.id, :isGrading => true %>
        <% course_apps = Grading.where :course_id => course.id %>
        <tr>
          <td style="text-align:center"><%= course.coursenum %></td>
          <td style="text-align:center"><%= course.sectionnum %></td>
          <td><%= course.coursename %></td>
          <td><%= course.days %></td>
          <td style="text-align:center"><%= course.starttime %></td>
          <td style="text-align:center"><%= course.endtime %></td>
          <td style="text-align:center"><%= course.enrolled %></td>
          <td style="text-align:center"><%= course.waitlist %></td>

          <% # Make sure there are graders, then output number of them %>
          <% if graders != nil %>
            <td style="text-align:center"><%= graders.length %></td>
          <% end %>

          <% # Make sure there are applications, then output them for admins only %>
          <% if (current_user.user_type == 3 || current_user.user_type == 2) && course_apps != nil %>
            <td style="text-align:center"><%= course_apps.length %></td>
          <% end %>

          <td><%= link_to 'Class Info', course %></td>

          <% # If the user is a student, allow them to Edit or Create applications %>
          <% if current_user.user_type == 1 %>

            <% existing_app = nil %>
            <% stu_apps.each do |app| %>
              <% if app.course_id == course.id %>
                <% existing_app = app; %>
              <% end %>
            <% end %>

            <% if existing_app != nil %>
              <td><%= link_to 'Edit App', edit_grading_path(existing_app, :course_id => course.id) %></td>
            <% else %>
              <td><%= link_to 'TA Apply', new_grading_path(:course_id => course.id) %></td>
            <% end %>

          <% # If the user is an instructor or admin, allow them to view a list of applications %>
          <% else %>
          
            <td><%= link_to 'Show Applications', gradings_path(:course_id => course.id) %></td>

          <% end %> 

          <% # All users are able to view a list of graders %>
          <td><%= link_to 'Show Graders', users_path(:course_id => course.id) %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<script>
  // https://stackoverflow.com/questions/51187477/how-to-filter-a-html-table-using-simple-javascript
  function myFunction(ele) {
    var filter, table, tr, td, i;
    filter = ele.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 2; i < tr.length; i++) {
      // Hide the row initially.
      tr[i].style.display = "none";

      var idStr = ele.id;
      var idNum = idStr.substring(3);
      var input = tr[1].getElementsByTagName("input");
      for (j = 0; j < input.length; j++) {
        if (j != idNum){
          input[j].value = "";
        }
      }
      cell = tr[i].getElementsByTagName("td")[idNum];
      if (cell) {
        if (cell.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } 
      }
    }
  }
</script>

<% # If not signed in, redirect to sign-in page %>
<% else %>
  <% controller.redirect_to new_user_session_path %>
<% end %>

wsl/app/views/courses/new.html.erb
<% #Page for adding courses, not used for project 4, generated by rails%>

<% <h1>New Course</h1> %>

<% render 'form', course: @course %>

<% link_to 'Back', courses_path %>

wsl/app/views/courses/show.html.erb
<% #Page that shows details of individual courses, generated by rails %>

<% #If signed-in, show courses %>
<% if user_signed_in? %>
  <% content_for :title do %>
    Course details
  <% end %>


  <p id="notice"><%= notice %></p>

  <p>
    <strong>Course Number:</strong>
    <%= @course.coursenum %>
  </p>

  <p>
    <strong>Section number:</strong>
    <%= @course.sectionnum %>
  </p>

  <p>
    <strong>Course name:</strong>
    <%= @course.coursename %>
  </p>

  <p>
    <strong>Days:</strong>
    <% if @course.days != '' %>
      <%= @course.days %>
    <% else %>
      TBD
    <% end %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= @course.starttime %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= @course.endtime %>
  </p>

  <p>
    <strong>Enrolled:</strong>
    <%= @course.enrolled %>
  </p>

  <p>
    <strong>Waitlist:</strong>
    <%= @course.waitlist %>
  </p>

  <p>
    <strong>Teacher Name:</strong>
    <% user = User.find @course.user_id%>
    <%= user.fname + " " + user.lname %>
  </p>

  <%= link_to 'Back to courses', courses_path %>


<% #If not signed in, redirect to sign-in page %>
<% else %>
  <% controller.redirect_to new_authentication_session_path %>
<% end %>